// <auto-generated />
using System;
using LoanAPIUpdate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanAPIUpdate.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425043224_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LoanAPIUpdate.Models.EMISchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("EMIAmount")
                        .HasColumnType("REAL");

                    b.Property<double>("InterestComponent")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("PrincipalComponent")
                        .HasColumnType("REAL");

                    b.Property<double>("RemainingBalance")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("EMISchedules");
                });

            modelBuilder.Entity("LoanAPIUpdate.Models.Loan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DocsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EMIAmount")
                        .HasColumnType("REAL");

                    b.Property<double>("InterestRate")
                        .HasColumnType("REAL");

                    b.Property<string>("LoanType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TermInMonths")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalPaid")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalPayable")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoanId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LoanAPIUpdate.Models.EMISchedule", b =>
                {
                    b.HasOne("LoanAPIUpdate.Models.Loan", "Loan")
                        .WithMany("EMISchedules")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LoanAPIUpdate.Models.Loan", b =>
                {
                    b.Navigation("EMISchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
